"""
Email service for ClientCreate.

Uses Gmail API to send summary emails after client creation.
"""

import base64
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import Optional, Tuple, List

from logger_setup import log_info, log_error, log_warning


class EmailService:
    """Service for sending emails via Gmail API."""

    def __init__(self, gmail_service=None):
        """
        Initialize email service.

        Args:
            gmail_service: Gmail API service object (from Google Drive service)
        """
        self.gmail_service = gmail_service
        self.sender_email: Optional[str] = None

    def set_gmail_service(self, gmail_service, sender_email: str):
        """
        Set the Gmail service after authentication.

        Args:
            gmail_service: Gmail API service object
            sender_email: Authenticated user's email address
        """
        self.gmail_service = gmail_service
        self.sender_email = sender_email

    def is_configured(self) -> bool:
        """Check if email service is configured and ready."""
        return self.gmail_service is not None and self.sender_email is not None

    def send_summary_email(
        self,
        to_emails: List[str],
        company_name: str,
        domain: str,
        drive_folder_url: str,
        hubspot_company_url: str,
        hubspot_deal_url: str,
        additional_info: Optional[str] = None
    ) -> Tuple[bool, Optional[str]]:
        """
        Send a client creation summary email.

        Args:
            to_emails: List of recipient email addresses
            company_name: Name of the created company
            domain: Company domain
            drive_folder_url: URL to Google Drive folder
            hubspot_company_url: URL to HubSpot company
            hubspot_deal_url: URL to HubSpot deal
            additional_info: Optional additional information to include

        Returns:
            Tuple of (success, error_message)
        """
        if not self.is_configured():
            return False, "Email service not configured"

        try:
            subject = f"New Client Created: {company_name}"

            # Build HTML body
            html_body = f"""
            <html>
            <body style="font-family: Arial, sans-serif; color: #333;">
                <h2 style="color: #2c5aa0;">New Client Created Successfully</h2>

                <table style="border-collapse: collapse; margin: 20px 0;">
                    <tr>
                        <td style="padding: 8px; font-weight: bold;">Company Name:</td>
                        <td style="padding: 8px;">{company_name}</td>
                    </tr>
                    <tr>
                        <td style="padding: 8px; font-weight: bold;">Domain:</td>
                        <td style="padding: 8px;">{domain}</td>
                    </tr>
                </table>

                <h3>Links</h3>
                <ul style="line-height: 1.8;">
                    <li><a href="{drive_folder_url}">Google Drive Folder</a></li>
                    <li><a href="{hubspot_company_url}">HubSpot Company</a></li>
                    <li><a href="{hubspot_deal_url}">HubSpot Deal</a></li>
                </ul>

                {f'<h3>Additional Information</h3><p>{additional_info}</p>' if additional_info else ''}

                <hr style="border: none; border-top: 1px solid #ddd; margin: 30px 0;">
                <p style="color: #888; font-size: 12px;">
                    This email was automatically generated by ClientCreate.
                </p>
            </body>
            </html>
            """

            # Also create plain text version
            text_body = f"""
New Client Created Successfully

Company Name: {company_name}
Domain: {domain}

Links:
- Google Drive Folder: {drive_folder_url}
- HubSpot Company: {hubspot_company_url}
- HubSpot Deal: {hubspot_deal_url}

{f'Additional Information:\\n{additional_info}' if additional_info else ''}

---
This email was automatically generated by ClientCreate.
            """

            # Create message
            message = MIMEMultipart('alternative')
            message['to'] = ', '.join(to_emails)
            message['from'] = self.sender_email
            message['subject'] = subject

            # Attach both plain text and HTML versions
            message.attach(MIMEText(text_body, 'plain'))
            message.attach(MIMEText(html_body, 'html'))

            # Encode message
            raw_message = base64.urlsafe_b64encode(message.as_bytes()).decode('utf-8')

            # Send via Gmail API
            self.gmail_service.users().messages().send(
                userId='me',
                body={'raw': raw_message}
            ).execute()

            log_info(f"Summary email sent to: {', '.join(to_emails)}")
            return True, None

        except Exception as e:
            log_error(f"Failed to send email: {e}")
            return False, str(e)

    def send_test_email(self, to_email: str) -> Tuple[bool, Optional[str]]:
        """
        Send a test email to verify configuration.

        Args:
            to_email: Recipient email address

        Returns:
            Tuple of (success, error_message)
        """
        if not self.is_configured():
            return False, "Email service not configured"

        try:
            message = MIMEText("This is a test email from ClientCreate.")
            message['to'] = to_email
            message['from'] = self.sender_email
            message['subject'] = "ClientCreate - Test Email"

            raw_message = base64.urlsafe_b64encode(message.as_bytes()).decode('utf-8')

            self.gmail_service.users().messages().send(
                userId='me',
                body={'raw': raw_message}
            ).execute()

            log_info(f"Test email sent to: {to_email}")
            return True, None

        except Exception as e:
            log_error(f"Failed to send test email: {e}")
            return False, str(e)


# Singleton instance
_email_service: Optional[EmailService] = None


def get_email_service() -> EmailService:
    """Get or create the email service instance."""
    global _email_service
    if _email_service is None:
        _email_service = EmailService()
    return _email_service
